###############################################################################
###############                GENERAL PARAMETERS               ###############
###############################################################################

OUTPUT: results/
METADATA: data/metadata.txt
SCRIPTS: ../workflow/scripts/

###############################################################################
###############                     RAW DATA                    ###############
###############################################################################

# Path to folder containing gzipped raw fastq data
RAW_DATA: data

# Is the data Paired End
PAIRED_END: True


###############################################################################
###############                CONDITIONAL RULES                ###############
###############################################################################

RUN_FASTQC: True
RUN_STAR: True
RUN_EAGLE: True
RUN_FEATURECOUNTS: True
RUN_EDGER: True


###############################################################################
###############                    ALIGNMENT                    ###############
###############################################################################

# Paths to the folder of the parental genome assemblies

GENOME_DIR_1: data/genome1/
GENOME_DIR_2: data/genome2/

GENOME_PARENT_1: g1.fa
GENOME_PARENT_2: g2.fa


###############################################################################
##############                 DOWNSTREAM ANALYSES               ##############
###############################################################################

# Path to annotation files
ANNOTATION_PARENT_1: data/genome1/anno1.gtf
ANNOTATION_PARENT_2: data/genome2/anno2.gtf

###############################################################################
###############                    FEATURE COUNT                ###############
###############################################################################

# Desired parameters
FC_PARAMS: ""

###############################################################################
##############                        edgeR                      ##############
###############################################################################

# Minimum count 
MIN_COUNT: 100