###############################################################################
###############                GENERAL PARAMETERS               ###############
###############################################################################

OUTPUT: results/
METADATA: data/metadata.txt

###############################################################################
###############                     RAW DATA                    ###############
###############################################################################

# Path to folder containing gzipped raw fastq data
RAW_DATA: data

###############################################################################
###############                CONDITIONAL RULES                ###############
###############################################################################

RUN_FASTQC: True
RUN_STAR: True
RUN_EAGLE: True


###############################################################################
###############                    ALIGNMENT                    ###############
###############################################################################

# Paths to the folder of the parental genome assemblies

GENOME_DIR_1: data/genome1/
GENOME_DIR_2: data/genome2/

GENOME_PARENT_1: g1.fa
GENOME_PARENT_2: g2.fa