###############################################################################
###############                GENERAL PARAMETERS               ###############
###############################################################################

OUTPUT: output/
METADATA: test/metadata.txt

###############################################################################
###############                     RAW DATA                    ###############
###############################################################################

# Path to folder containing gzipped raw fastq data
RAW_DATA: test

###############################################################################
###############                CONDITIONAL RULES                ###############
###############################################################################

RUN_FASTQC: True
RUN_STAR: True


###############################################################################
###############                    ALIGNMENT                    ###############
###############################################################################

# Paths to the folder of the parental genome assemblies

GENOME_DIR_1: test/genome1
GENOME_DIR_2: test/genome2

GENOME_PARENT_1: Ahal_ref.fa
GENOME_PARENT_2: Alyr_ref.fa