###############################################################################
###############                GENERAL PARAMETERS               ###############
###############################################################################

OUTPUT: results/
METADATA: .test/data/metadata.txt

###############################################################################
###############                     RAW DATA                    ###############
###############################################################################

# Path to folder containing gzipped raw fastq data
RAW_DATA: .test/data

###############################################################################
###############                CONDITIONAL RULES                ###############
###############################################################################

RUN_FASTQC: True
RUN_STAR: True


###############################################################################
###############                    ALIGNMENT                    ###############
###############################################################################

# Paths to the folder of the parental genome assemblies


GENOME_DIR_1: .test/data/genome1/
GENOME_DIR_2: .test/data/genome2/

GENOME_PARENT_1: g1.fa
GENOME_PARENT_2: g2.fa